
import { StoreSettings, Product, Banner, Language } from './types';

export const INITIAL_SETTINGS: StoreSettings = {
  gstPercent: 5,
  deliveryCharge: 40,
  freeDeliveryThreshold: 500,
  merchantVpa: '8317570742@kotak811',
  merchantName: 'Ahaa Masala',
  adminUsername: 'admin',
  adminPasswordHash: 'admin123', // In a real app, this would be a secure hash
  allowCod: true,
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Coriander Powder',
    nameTe: 'ధనియాల పొడి',
    description: 'Fresh aromatic ground coriander seeds.',
    descriptionTe: 'కూరలకు రుచినిచ్చే సువాసనగల ధనియాల పొడి.',
    image: 'https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v1', weight: '50g', price: 40, stock: 100 },
      { id: 'v2', weight: '100g', price: 75, stock: 100 },
      { id: 'v3', weight: '200g', price: 140, stock: 50 },
    ],
    active: true,
  },
  {
    id: 'p2',
    name: 'Chicken Masala',
    nameTe: 'చికెన్ మసాలా',
    description: 'Perfect blend for spicy and tasty chicken curry.',
    descriptionTe: 'ఘాటైన మరియు రుచికరమైన చికెన్ కూర కోసం సరైన మిశ్రమం.',
    image: 'https://images.unsplash.com/photo-1626322889240-a4a58b0213d8?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v1', weight: '50g', price: 50, stock: 100 },
      { id: 'v2', weight: '100g', price: 90, stock: 100 },
      { id: 'v3', weight: '200g', price: 170, stock: 50 },
    ],
    active: true,
  },
  {
    id: 'p3',
    name: 'Garam Masala',
    nameTe: 'గరం మసాలా',
    description: 'Traditional aromatic spice blend for all dishes.',
    descriptionTe: 'అన్ని వంటకాలకు ఘుమఘుమలాడే సంప్రదాయ మసాలా.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v1', weight: '50g', price: 60, stock: 150 },
      { id: 'v2', weight: '100g', price: 110, stock: 100 },
      { id: 'v3', weight: '200g', price: 210, stock: 50 },
    ],
    active: true,
  },
  {
    id: 'p4',
    name: 'Mutton Masala',
    nameTe: 'మటన్ మసాలా',
    description: 'Rich spices for tender and spicy mutton gravy.',
    descriptionTe: 'మటన్ కూర కోసం ప్రత్యేకంగా తయారు చేసిన ఘాటైన మసాలా.',
    image: 'https://images.unsplash.com/photo-1543825988-757045b41297?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v1', weight: '50g', price: 55, stock: 100 },
      { id: 'v2', weight: '100g', price: 100, stock: 100 },
      { id: 'v3', weight: '200g', price: 190, stock: 50 },
    ],
    active: true,
  },
  {
    id: 'p5',
    name: 'Rasam Powder',
    nameTe: 'రసం పొడి',
    description: 'Authentic blend for homemade tangy rasam.',
    descriptionTe: 'ఇంటి రుచితో కూడిన కమ్మని రసం కోసం.',
    image: 'https://images.unsplash.com/photo-1606914502280-99c0160d5b6e?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v1', weight: '50g', price: 45, stock: 100 },
      { id: 'v2', weight: '100g', price: 85, stock: 100 },
      { id: 'v3', weight: '200g', price: 160, stock: 50 },
    ],
    active: true,
  },
  {
    id: 'p6',
    name: 'Chettinad Pepper Masala',
    nameTe: 'చెట్టినాడ్ పెప్పర్ మసాలా',
    description: 'Spicy pepper blend for Chettinad style dishes.',
    descriptionTe: 'చెట్టినాడ్ వంటకాల కోసం మిరియాల ఘాటు కలిగిన మసాలా.',
    image: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v1', weight: '50g', price: 65, stock: 100 },
      { id: 'v2', weight: '100g', price: 120, stock: 100 },
      { id: 'v3', weight: '200g', price: 230, stock: 50 },
    ],
    active: true,
  },
  {
    id: 'p7',
    name: 'Sambar Powder',
    nameTe: 'సాంబార్ పొడి',
    description: 'Classic South Indian sambar mix.',
    descriptionTe: 'దక్షిణ భారత సాంబార్ రుచి కోసం సరైన ఎంపిక.',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=400&q=80',
    variants: [
      { id: 'v1', weight: '50g', price: 45, stock: 100 },
      { id: 'v2', weight: '100g', price: 85, stock: 100 },
      { id: 'v3', weight: '200g', price: 160, stock: 50 },
    ],
    active: true,
  },
];

export const INITIAL_BANNERS: Banner[] = [
  { id: 'b1', image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1200&q=80', alt: 'Premium Spices', active: true, order: 1 },
  { id: 'b2', image: 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=1200&q=80', alt: 'Authentic Flavor', active: true, order: 2 },
];

export const TRANSLATIONS = {
  [Language.EN]: {
    home: 'Home',
    cart: 'Cart',
    checkout: 'Checkout',
    addToCart: 'Add to Cart',
    added: 'Added!',
    outOfStock: 'Out of Stock',
    total: 'Total',
    subtotal: 'Subtotal',
    gst: 'GST',
    delivery: 'Delivery',
    discount: 'Discount',
    payNow: 'Pay Now',
    cod: 'Cash on Delivery',
    upi: 'UPI Online Payment',
    completeOrder: 'Complete your order now',
    payNote: 'Pay after taking screenshot',
    uploadScreenshot: 'Upload Payment Screenshot',
    name: 'Full Name',
    mobile: 'Mobile Number',
    houseNo: 'Flat / House No',
    address: 'Address',
    landmark: 'Landmark',
    placeOrder: 'Place Order',
    adminPanel: 'Admin Panel',
    login: 'Login',
    dashboard: 'Dashboard',
    products: 'Products',
    orders: 'Orders',
    settings: 'Settings',
    emptyCart: 'Your cart is empty',
    continueShopping: 'Continue Shopping',
    orderSuccess: 'Order Placed Successfully!',
    sendWhatsApp: 'Send Details on WhatsApp',
    attachProof: 'Please attach the payment screenshot in WhatsApp before sending.',
    codConfirm: 'COD Order - Please confirm.',
    apply: 'Apply',
    remove: 'Remove',
    couponCode: 'Coupon Code',
    qty: 'Qty',
    price: 'Price',
    weight: 'Weight',
    mandal: 'Mandal',
    district: 'District',
    city: 'City',
    state: 'State',
    pincode: 'Pincode',
    trackOrder: 'Track Order',
    orderId: 'Order ID',
    track: 'Track Status',
    orderStatus: 'Current Status',
    orderNotFound: 'Order not found. Please check details.',
    statusSteps: {
      placed: 'Order Placed',
      confirmed: 'Confirmed',
      delivered: 'Delivered',
      cancelled: 'Cancelled'
    }
  },
  [Language.TE]: {
    home: 'హోమ్',
    cart: 'కార్ట్',
    checkout: 'చెక్అవుట్',
    addToCart: 'కార్ట్‌కు జోడించండి',
    added: 'జోడించబడింది!',
    outOfStock: 'స్టాక్ లేదు',
    total: 'మొత్తం',
    subtotal: 'ఉప మొత్తం',
    gst: 'GST',
    delivery: 'డెలివరీ',
    discount: 'రాయితీ',
    payNow: 'ఇప్పుడే చెల్లించండి',
    cod: 'క్యాష్ ఆన్ డెలివరీ (COD)',
    upi: 'UPI ఆన్‌లైన్ చెల్లింపు',
    completeOrder: 'మీ ఆర్డర్‌ని ఇప్పుడే పూర్తి చేయండి',
    payNote: 'స్క్రీన్‌షాట్ తీసుకున్న తర్వాత చెల్లించండి',
    uploadScreenshot: 'చెల్లింపు స్క్రీన్‌షాట్‌ను అప్‌లోడ్ చేయండి',
    name: 'పూర్తి పేరు',
    mobile: 'మొబైల్ నంబర్',
    houseNo: 'ఫ్లాట్ / ఇంటి నంబర్',
    address: 'చిరునామా',
    landmark: 'ల్యాండ్‌మార్క్ (గుర్తు)',
    placeOrder: 'ఆర్డర్ చేయండి',
    adminPanel: 'అడ్మిన్ ప్యానెల్',
    login: 'లాగిన్',
    dashboard: 'డ్యాష్‌బోర్డ్',
    products: 'ఉత్పత్తులు',
    orders: 'ఆర్డర్లు',
    settings: 'సెట్టింగ్‌లు',
    emptyCart: 'మీ కార్ట్ ఖాళీగా ఉంది',
    continueShopping: 'షాపింగ్ కొనసాగించండి',
    orderSuccess: 'ఆర్డర్ విజయవంతంగా చేయబడింది!',
    sendWhatsApp: 'వాట్సాప్‌లో వివరాలను పంపండి',
    attachProof: 'దయచేసి పంపే ముందు వాట్సాప్‌లో చెల్లింపు స్క్రీన్‌షాట్‌ను జత చేయండి.',
    codConfirm: 'COD ఆర్డర్ - దయచేసి నిర్ధారించండి.',
    apply: 'వర్తించు',
    remove: 'తొలగించు',
    couponCode: 'కూపన్ కోడ్',
    qty: 'పరిమాణం',
    price: 'ధర',
    weight: 'బరువు',
    mandal: 'మండలం',
    district: 'జిల్లా',
    city: 'నగరం',
    state: 'రాష్ట్రం',
    pincode: 'పిన్ కోడ్',
    trackOrder: 'ఆర్డర్ ట్రాక్ చేయండి',
    orderId: 'ఆర్డర్ ఐడి',
    track: 'ట్రాక్ చేయండి',
    orderStatus: 'ప్రస్తుత స్థితి',
    orderNotFound: 'ఆర్డర్ కనుగొనబడలేదు. దయచేసి వివరాలను తనిఖీ చేయండి.',
    statusSteps: {
      placed: 'ఆర్డర్ చేయబడింది',
      confirmed: 'నిర్ధారించబడింది',
      delivered: 'డెలివరీ చేయబడింది',
      cancelled: 'రద్దు చేయబడింది'
    }
  }
};
